version: "3.9"
volumes:
  data:
  config:
  plugin:
networks:
  es:
services:
  elasticsearch:
    image: elasticsearch:8.1.1
#	container_name: myes
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - "es"
    environment:
      - "discovery.type=single-node"
    volumes:
      - data:/usr/share/elasticsearch/data
      - config:/usr/share/elasticsearch/config
      - plugin:/usr/share/elasticsearch/plugins

  kibana:
    image: kibana:8.1.1
#	container_name: mykibana
    ports:
      - "5601:5601"
    networks:
      - "es"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  redis:
    image: redis:latest
#	container_name: myredis
#	restart: "no"
    ports:
      - "6379:6379"
    networks:
      - "es"
    volumes:
      - ./redis.conf:/etc/redis/redis.conf
      - ./redis_data:/data
    command: redis-server /etc/redis/redis.conf
    privileged: true